import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import { SetStateAction, useEffect, useState } from "react";
import UserInterface from "@/components/UserInterface/UserInterface";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const cards = [
    {
      title: "Documentation",
      description: "Find in-depth information about Next.js features and API.",
      link: "https://nextjs.org/docs",
      image: "/images/docs.svg",
    },
    {
      title: "Learn",
      description: "Learn about Next.js in an interactive course with quizzes!",
      link: "https://nextjs.org/learn",
      image: "/images/learn.svg",
    },
    {
      title: "Templates",
      description: "Discover and deploy boilerplate example Next.js projects.",
      link: "https://vercel.com/templates?framework=next.js",
      image: "/images/templates.svg",
    },
    {
      title: "Deploy",
      description:
        "Instantly deploy your Next.js site to a shareable URL with Vercel.",
      link: "https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
      image: "/images/deploy.svg",
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}></div>
        <h1 className={styles.h1}>Medicines Label Summarizer</h1>
        <div className={styles.center}>
          <UserInterface />
        </div>
        <div className={styles.grid}>
          {cards.map(card => (
            <a
              key={card.title}
              href={card.link}
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                {card.title} <span>-&gt;</span>
              </h2>
              <p className={inter.className}>{card.description}</p>
            </a>
          ))}
        </div>
      </main>
    </>
  );
}
